--- 
- gather_facts: false
  hosts: all
  remote_user: root
  tasks: 

  - name: Installing git
    become: true
    apt:
      name: git
      update_cache: yes

  - name: Installing psmisc
    become: true
    apt:
      name: psmisc
      update_cache: yes

  - name: Installing locales
    become: true
    apt:
      name: locales
      update_cache: yes

  - name: Installing expect
    become: true
    apt:
      name: expect
      update_cache: yes

  - name: Cloning appscale
    become: true
    git:
      repo: git://github.com/AppScale/appscale.git
      dest: /root/appscale

  - name: Cloning appscale-tools
    become: true
    git:
      repo: git://github.com/AppScale/appscale-tools.git
      dest: /root/appscale-tools

  - name: Get bootstrap.sh
    become: true
    get_url:
      url: https://bootstrap.appscale.com
      dest: /root/bootstrap.sh

  - name: Update appscale_build env
    become: true
    replace:
      path: /root/appscale/debian/appscale_build.sh
      regexp: '^export IN_DOCKER=\"no\"'
      replace: 'export IN_DOCKER="yes"'

  - name: Generating locale
    become: true
    shell: locale-gen "en_US.UTF-8"

    #  - name: Installing appscale from source
    #become: true
    #shell: bash bootstrap.sh
    #args:
    #  chdir: /root


